### ISSUE TITLE
flom daemon starts during boot but doesn't stay running

### ISSUE THREAD

**Issue by slberger** [tiian/flom#24] opened 2022-08-16 01:03 UTC
I've been running flom 1.5.20 on CentOS 7 for some time now. It starts in /etc/rc.local with the command:

/usr/local/bin/flom -a _fqdn.domain.com_ -d -1 -- true

and the daemon is there after the boot process completes.

I'm now trying to get flom to run on an AlmaLinux 8 system. /etc/rc.local has been deprecated so I followed a Red Hat article for how to start a process near the end of the boot process using systemd: https://access.redhat.com/solutions/1751263

According to /var/log/messages, the flom process starts up and it logs the same entries as it does on CentOS 7, but the daemon process exits and is not running when the boot completes. The version of flom on the AlmaLinux system is 1.5.23-dev. I have tried many things but nothing seems to start the daemon and keep it running during boot.

If I issue the same flom command interactively, the daemon starts and stays running. I'm out of ideas at this point. Thank you for any help you can provide.

**Comment by tiian** [comment] 2022-08-16 20:17
Hi,
a first note, probably not the root cause of the issue, is related to the version you are using.
1.5.23-dev is neither a tag in git nor a tarball in Sourceforge, but the last commit in the git master branch: please build FLoM using an official release, like the last one: 1.5.22
I don't remember what are the differences added in the last commits, but it's much better to stay on the safe side.

Have you tried to activate tracing by mean of environment variable FLOM_TRACE_MASK?
File [https://github.com/tiian/flom/blob/master/src/flom_trace.h](https://github.com/tiian/flom/blob/master/src/flom_trace.h) documents which features can be traced, but you can even start with everything just to dig a little bit:

    export FLOM_TRACE_MASK=0xffffffff

Use the options

    -t, --daemon-trace-file=FILENAME
    -T, --command-trace-file=FILENAME

as documented in the man page to send traces to specific files; compare traces of an environment where FLoM daemon boots properly with the traces of the environment where FLoM does not boot as desired.

**Comment by slberger** [comment] 2022-08-16 22:44
Thank you for the fast response. I removed all remnants of 1.5.23-dev from the system and built 1.5.22. I had one problem with the configure script revolving around COND_JAVADOC_HTML5 that I didn't have when building the dev version. I fixed this by adding the extra code that was in the dev configure file:

```
else
         if false; then
  COND_JAVADOC_HTML5_TRUE=
  COND_JAVADOC_HTML5_FALSE='#'
else
  COND_JAVADOC_HTML5_TRUE='#'
  COND_JAVADOC_HTML5_FALSE=
fi
```


 at the end of the block that's titled "checking if javadoc support HTML5"

After that the make and make install ran fine.

I am still having the same problem but adding the traces reveal the following:

I have a script, very-last, that looks like this:

```
#!/bin/bash
export FLOM_TRACE_MASK=0xffffffff
/usr/local/bin/flom -a waec5.qg.com --daemon-lifespan="-1" --daemon-trace-file=/var/log/flomdt --command-trace-file=/var/log/flomct -- true
```
When I run that script interactively, the flom daemon stays running and the last 2 lines in the daemon-trace-file are:

```
2022-08-16 17:31:38.981987 [6343/0x2339c00] flom_locker_loop: locker termination already started, using infinite poll timeout...
2022-08-16 17:31:38.981996 [6343/0x2339c00] flom_locker_loop: entering poll using -1 timeout milliseconds...
```
However, if I try to run that same script under control of systemd by issuing the command:

systemctl start very-last

the daemon starts but exits immediately. The last two lines in the daemon trace file are:

```
2022-08-16 17:34:33.902087 [6736/0x1c15c00] flom_locker_loop: setting default timeout: 1000 milliseconds
2022-08-16 17:34:33.902096 [6736/0x1c15c00] flom_locker_loop: entering poll using 1000 timeout milliseconds...
```
So this tells us what's happening. I can't figure out how to get the -1 daemon lifespan to be honored when starting the daemon using systemd. The documentation states that if the -d option is ommitted, the default is 5000 msec. I tried that just to see what would happen and it still used 1000 msec as the timeout.

The systemd service file looks like this and is directly out of the Red Hat article:

```
[Unit]
Description=Very last service
After=default.target

[Service]
Type=oneshot
ExecStart=/usr/local/sbin/very-last

[Install]
WantedBy=default.target
```

**Comment by tiian** [comment] 2022-08-17 20:32
The trace should contains the messages about the configuration parameter at the early start-up.
To isolate that messages use:

    export FLOM_TRACE_MASK=0x00000002

Configuration is performed at the very beginning, before the trace file name is captured, so typically it can be retrieved from stderr even if option 

    -t, --daemon-trace-file=FILENAME

is specified.
Try to understand if the parameters on the command line are really passed and interpreted correctly by the process.

**Comment by slberger** [comment] 2022-08-17 23:20
I didn't have a flom.conf file and the -d option was not showing up in the logs or in stderr whether I successfully started flom manually or failed to start it via systemd. I added a flom.conf file and set the lifetime to -1 but the daemon trace was still showing a timeout of 1000 msec. I tried a different method of starting it up using cron and the @reboot option. That successfully started flom during boot. So I guess I'm happy, though there still seems to be some kind of issue with the process of starting it under control of systemd.

I did look to see if I could find somewhere in the code where the timeout was getting set to 1000 msec. There is a constant, FLOM_LOCKER_POLL_TIMEOUT, defined in flom_locker.h, which is set to 1000. In flom_locker.c there is the section of code below:

```
            if (0 <= (timeout = flom_locker_loop_get_timeout(
                          &next_deadline))) {
                FLOM_TRACE(("flom_locker_loop: timeout was requested by the "
                            "resource: %d milliseconds\n", timeout));
            } else if (locker->idle_periods > FLOM_LOCKER_MAX_IDLE_PERIODS) {
                /* the only possible event comes from main thread, using
                   a shorter time-out would be useless */
                timeout = -1;
                FLOM_TRACE(("flom_locker_loop: locker termination already "
                            "started, using infinite poll timeout...\n"));
            } else if (locker->idle_periods > 0) {
                /* there's a chance this locker would start termination
                   because there are no connected clients */
                timeout = FLOM_LOCKER_POLL_TIMEOUT;
                FLOM_TRACE(("flom_locker_loop: possible locker termination "
                            "in the next few milliseconds, using a short "
                            "poll timeout...\n"));
            } else if (locker->idle_periods == 0 &&
                       locker->idle_lifespan > 0) {
                /* time-out must be fixed to resource lifespan as requested
                   by the client */
                timeout = locker->idle_lifespan;
                FLOM_TRACE(("flom_locker_loop: resource timeout asked by "
                            "caller (%d milliseconds)\n", timeout));
            } else {
                timeout = FLOM_LOCKER_POLL_TIMEOUT;
                FLOM_TRACE(("flom_locker_loop: setting default timeout: "
                            "%d milliseconds\n", timeout));
            }
            FLOM_TRACE(("flom_locker_loop: entering poll using %d "
                        "timeout milliseconds...\n", timeout));
```

I don't profess to understand the code but I do see that the catchall else block in this if-then-else block does set the timeout to 1000 msec, along with emitting the message that we see in the deamon trace file when an attempt is made to start flom using systemctl.

Thank you for all of your assistance.

**Comment by tiian** [comment] 2022-08-20 11:14
Hi,
good to know you have found an alternative way to get FLoM running, but the point you raised might deserve some further investigation if you are willing to perform it.
Could you start the daemon with verbose flag active ("-V", or "--verbose")?

You should get on stdout something like:

    tiian@ubuntu1004:~/flom$ flom -V -d -1
    [Trace]/DaemonTraceFile=''
    [Trace]/CommandTraceFile=''
    [Trace]/AppendTraceFile=0
    [Trace]/Verbose=1
    [Resource]/Name='_RESOURCE'
    [Resource]/Timeout=-1
    [Resource]/Quantity=1
    [Resource]/LockMode=5
    [Resource]/Create=1
    [Resource]/IdleLifespan=0
    [Daemon]/SocketName=''
    [Daemon]/Lifespan=-1
    [Daemon]/UnicastAddress=''
    [Daemon]/UnicastPort=28015
    [Daemon]/MulticastAddress=''
    [Daemon]/MulticastPort=28015
    [Monitor]/IgnoredSignals=''
    [Network]/NetworkInterface=''
    [Network]/DiscoveryAttempts=2
    [Network]/DiscoveryTimeout=500
    [Network]/DiscoveryTTL=1
    [Network]/TcpKeepaliveTime=60
    [Network]/TcpKeepaliveIntvl=10
    [Network]/TcpKeepaliveProbes=6
    [TLS]/TlsCertificate=''
    [TLS]/TlsPrivateKey=''
    [TLS]/TlsCaCertificate=''
    [TLS]/TlsCheckPeerId=0

the interesting configuration key is

    [Daemon]/Lifespan=-1

independently where you set it (config file, command line).

I have a couple of suspects:

1. some "strange" shell behavior in passing the "-d -1" argument to the process during the boostrap
2. some automatic flom daemon activation like in the following scenario: before the daemon you want to activate (parameter "-d -1"), a simple flom command is issued and it starts by itself a short term daemon because there's no an active daemon; few milliseconds later the explicit daemon activation fails because there's an already running daemon, but the running daemon is the automatically triggered one and it closes after 5 seconds.

**Comment by slberger** [comment] 2022-08-20 17:24
I went back and re-created the necessary files to start flom via systemd. The script that ultimately gets executed is:

```
#!/bin/bash
/usr/local/bin/flom -a fqdn.domain.com -V -d -1 -- true >/tmp/flomstdout 2>/tmp/flomstderr
```
When I simply execute this script from bash, [Daemon]/Lifespan=-1 is in the flomstdout file and the flom daemon is running. When I stop it and try running the same script by using systemctl start very-last, which executes the script above, I also get [Daemon]Lifespan=-1 in the flomstdout file but the flom daemon exits immediately.

**Comment by tiian** [comment] 2022-09-03 07:14
Hi, could you try to execute it, just for testing, without "-a fqdn.domain.com"?
Specifying "-a" requires to open and bind an Internet TCP/IP address for listening: if the network is not yet ready or the network is restarted by a later boot step, that could be an issue.

**Comment by slberger** [comment] 2022-09-23 19:15
I tried removing the -a fqdn.domain.com as you suggested. I didn't do a reboot to check but after killing off the process and doing:

systemctl start xxxx

as documented in https://access.redhat.com/solutions/1751263, the process started and exited immediately, as before.

**Comment by tiian** [comment] 2022-12-10 11:18
@klesteb : thank you so much for the config example!

@slberger : I tested the config provided by @klesteb and it works smoothly with a minor change both on CentOS 7 and CentOS 8. I don't have an AlmaLinux 8 in my test set, but in theory it should not be different than CentOS 8.

Here is the version for CentOS 7/8 of the 
/etc/systemd/system/flom.service
config file:

    [Unit]
    Description=FLoM - Free Lock Manager
    Documentation=man:flom(1)
    After=network-online.target multi-user.target
    
    [Service]
    Type=forking
    ExecStart=/usr/local/bin/flom -V -a %H -A 239.255.0.1 -d -1 -- true
    
    [Install]
    WantedBy=default.target
    

In some cases %H is resolved with hostname instead of hostname.domainname: to workaround the issue you can alternatively use the IP address:

    [Service]
    Type=forking
    ExecStart=/usr/local/bin/flom -V -a 192.168.123.227 -A 239.255.0.1 -d -1 -- true

Please tell me if the above config works even for you.

**Closed** 2023-01-01 15:34 UTC
Labels: help wanted
